name = "kaleko-website-api"
type = "webpack"
webpack_config = "webpack.config.js"
compatibility_date = "2021-10-01"

account_id = "87867b42ad45c72b767a3fae88fb33fa"

zone_id = "2a36842a31ad183f908d745513801ffc"
routes = ["api.kaleko.ga/*"]

[vars]
GITHUB_USERNAME = "Kale-Ko"